branches:
  - main
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: 'conventionalcommits'
      releaseRules:
        - {type: patch, release: patch}
        - {type: minor, release: minor}
        - {type: major, release: major}
        - {type: perf, release: patch}
  - - '@semantic-release/release-notes-generator'
    - preset: 'conventionalcommits'
      presetConfig:
        types:
          - {type: feat, section: '🚀 Features'}
          - {type: fix, section: '🐛 Bug Fixes'}
          - {type: perf, section: '⚡ Performance'}
          - {type: refactor, section: '🚜 Refactor'}
          - {type: docs, section: '📚 Documentation'}
          - {type: test, section: '🧪 Testing'}
          - {type: style, section: '🎨 Styling'}
          - {type: revert, section: '◀️ Revert'}
          - {type: build, section: '🏗️ Build'}
          - {type: ci, section: '🔄 CI'}
          - {type: chore, section: '🧹 Chore'}
#        groupBy: type
        commitGroupsSort: ['feat', 'fix', 'perf', 'refactor', 'docs', 'test', 'style', 'revert', 'build', 'ci', 'chore']
  - '@semantic-release/git'
