branches:
  - main
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: 'conventionalcommits'
      releaseRules:
        - {type: patch, release: patch}
        - {type: minor, release: minor}
        - {type: major, release: major}
        - {type: perf, release: patch}
  - - '@semantic-release/release-notes-generator'
    - preset: 'conventionalcommits'
      writerOpts:
#        groupBy: type
        commitGroupsSort: ['feat', 'fix', 'perf', 'refactor', 'docs', 'test', 'style', 'revert', 'build', 'ci', 'chore']
        transform:
          feat: '🚀 Features',
          fix: '🐛 Bug Fixes',
          perf: '⚡ Performance',
          refactor: '🚜 Refactor',
          docs: '📚 Documentation',
          test: '🧪 Testing',
          style: '🎨 Styling',
          revert: '◀️ Revert',
          build: '🏗️ Build',
          ci: '🔄 CI',
          chore: '🧹 Chore'
  - '@semantic-release/git'
