branches:
  - main
plugins:
  - 'conventional-changelog-conventionalcommits'
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
      releaseRules:
        - type: patch
          release: patch
        - type: minor
          release: minor
        - type: major
          release: major
  - '@semantic-release/git'
