branches:
  - main
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: 'conventionalcommits'
      releaseRules:
        - {type: patch, release: patch}
        - {type: minor, release: minor}
        - {type: major, release: major}
        - {type: feat, release: minor}
        - {type: fix, release: patch}
        - {type: perf, release: patch}
        - {type: docs, release: false}
        - {type: test, release: patch}
        - {type: style, release: patch}
        - {type: revert, release: patch}
        - {type: build, release: false}
        - {type: ci, release: false}
        - {type: chore, release: patch}
  - - '@semantic-release/release-notes-generator'
    - preset: 'conventionalcommits'
      presetConfig:
        types:
          - {type: feat, section: '🚀 Features', hidden: false}
          - {type: fix, section: '🐛 Bug Fixes', hidden: false}
          - {type: perf, section: '⚡ Performance', hidden: false}
          - {type: refactor, section: '🚜 Refactor', hidden: false}
          - {type: docs, section: '📚 Documentation', hidden: false}
          - {type: test, section: '🧪 Testing', hidden: false}
          - {type: style, section: '🎨 Styling', hidden: false}
          - {type: revert, section: '◀️ Revert', hidden: false}
          - {type: build, section: '🏗️ Build', hidden: false}
          - {type: ci, section: '🔄 CI', hidden: false}
          - {type: chore, section: '🧹 Chore', hidden: false}
        commitGroupsSort: ['feat', 'fix', 'perf', 'refactor', 'docs', 'test', 'style', 'revert', 'build', 'ci', 'chore']
  - - '@semantic-release/changelog'
    - changelogFile: 'CHANGELOG.md'
      changelogTitle: "# Changelog\n\nAll notable changes to this project will be documented in this file."
  - - '@semantic-release/git'
    - assets: ['CHANGELOG.md']
      message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'
  - '@semantic-release/github'
